robot_base_joint_publisher:
  type: "joint_state_controller/JointStateController"
  publish_rate: 50

robot_base_velocity_controller:
  type: "diff_drive_controller/DiffDriveController"
  left_wheel: ['l_wheel_joint']
  right_wheel: ['r_wheel_joint']
  publish_rate: 50
  pose_covariance_diagonal: [0.001, 0.001, 1000000.0, 1000000.0, 1000000.0, 1000.0]
  twist_covariance_diagonal: [0.001, 0.001, 1000000.0, 1000000.0, 1000000.0, 1000.0]
  cmd_vel_timeout: 0.5
  wheel_separation : 0.230
  wheel_radius : 0.035
  base_frame_id: base_link
  odom_frame_id: odom
  enable_odom_tf: true
  wheel_separation_multiplier: 1.0
  wheel_radius_multiplier    : 1.0
  linear:
    x:
      has_velocity_limits    : true
      max_velocity           : 1.0  # m/s
      min_velocity           : -0.5 # m/s
      has_acceleration_limits: true
      max_acceleration       : 0.8  # m/s^2
      min_acceleration       : -0.4 # m/s^2
      has_jerk_limits        : true
      max_jerk               : 5.0  # m/s^3
  angular:
    z:
      has_velocity_limits    : true
      max_velocity           : 1.7  # rad/s
      has_acceleration_limits: true
      max_acceleration       : 1.5  # rad/s^2
      has_jerk_limits        : true
      max_jerk               : 2.5  # rad/s^3
